kaltura/src/main/java/org/sakaiproject/kaltura/model/KalturaItemWrapper.java
/**
 * Copyright 2010 Unicon (R) Licensed under the
 * Educational Community License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 *
 * http://www.osedu.org/licenses/ECL-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS"
 * BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package org.sakaiproject.kaltura.model;

import java.util.Date;

import com.kaltura.client.enums.KalturaMediaType;
import com.kaltura.client.types.KalturaMediaEntry;

public class KalturaItemWrapper {

    private KalturaMediaEntry entry;

    public KalturaItemWrapper(KalturaMediaEntry entry) {
        this.entry = entry;
    }

    public String getName() {
        return entry.name;
    }

    public String getDesc() {
        return entry.description;
    }

    public float getDuration() {
        return entry.duration;
    }

    public Date getDate() {
        return new Date(entry.createdAt* (1000l));
    }

    public int getWidth() {
        return entry.width;
    }

    public int getHeight() {
        return entry.height;
    }

    public String getType() {
        String type = "video";
        KalturaMediaType mediaType = entry.mediaType;
        type = mediaType.toString().toLowerCase();
        return type;
    }

    public String getThumbnail() {
        return entry.thumbnailUrl;
    }

    public String getKalturaId() {
        return entry.id;
    }


}

kaltura/src/main/java/org/sakaiproject/kaltura/tool/EditCollectionDetailsController.java
/**
 * Copyright 2010 Unicon (R) Licensed under the
 * Educational Community License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 *
 * http://www.osedu.org/licenses/ECL-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS"
 * BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package org.sakaiproject.kaltura.tool;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.sakaiproject.kaltura.logic.ExternalLogic;
import org.sakaiproject.kaltura.logic.MediaService;
import org.sakaiproject.kaltura.model.MediaCollection;
import org.sakaiproject.kaltura.mvc.command.CollectionForm;
import org.springframework.validation.BindException;
import org.springframework.validation.Errors;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.CancellableFormController;

/**
 * EditCollectionDetailsController handles creating new Kaltura
 * collections and editing the main title/description details of
 * existing collections.
 * 
 * @author Aaron Zeckoski, azeckoski@unicon.net
 * @author Jen Bourey, jbourey@unicon.net
 * @version $Revision: 120884 $
 */
public class EditCollectionDetailsController extends CancellableFormController {

    final protected Log log = LogFactory.getLog(getClass());

    /**
     * Default constructor
     */
    public EditCollectionDetailsController() {
        this.setCommandClass(CollectionForm.class);
    }

    /*
     * (non-Javadoc)
     * @see org.springframework.web.servlet.mvc.SimpleFormController#onSubmit(javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse, java.lang.Object, org.springframework.validation.BindException)
     */
    @Override
    protected ModelAndView onSubmit(HttpServletRequest request,
            HttpServletResponse response, Object command, BindException errors)
                    throws Exception {

        CollectionForm form = (CollectionForm) command;

        MediaCollection collection;

        if (StringUtils.isBlank(form.getId())) {
            // if this is a new collection, create a new collection on the Kaltura server
            String locationId = external.getCurrentLocationId(); 
            if (log.isDebugEnabled()) log.debug("Submit add collection in location: "+locationId);
            collection = mediaService.addCollection(form.getTitle(), locationId);
        } else {
            // otherwise, retrieve the current collection from Kaltura
            if (log.isDebugEnabled()) log.debug("Submit update collection: "+form.getId());
            collection = mediaService.getCollection(form.getId(), 0, 0);
        }

        // update the collection with the form information
        collection.setTitle(form.getTitle());
        collection.setDescription(form.getDescription());
        collection.setHidden(form.isHidden());
        collection.setSharing(form.getSharing());
        collection.setOwnerId(external.getCurrentUser().getUsername());

        // persist the collection update
        mediaService.updateCollection(collection);

        // add an appropriate message indicating collection has been edited successfully
        List<String> messageCodes = new ArrayList<String>();
        messageCodes.add("editCollectionDetails.saved");
        request.setAttribute("infos", messageCodes);

        // send the user back to the main collections listing
        String forwardUrl = "viewCollection.htm?collectionId=" + collection.getId();
        request.getRequestDispatcher(forwardUrl).forward(request, response);
        return null;

    }

    /*
     * (non-Javadoc)
     * @see org.springframework.web.servlet.mvc.AbstractFormController#formBackingObject(javax.servlet.http.HttpServletRequest)
     */
    @Override
    protected Object formBackingObject(HttpServletRequest request)
            throws Exception {

        CollectionForm form;

        String collectionId = request.getParameter("collectionId");
        if (!StringUtils.isBlank(collectionId)) {
            MediaCollection collection = mediaService.getCollection(collectionId, 0, 0);
            form = new CollectionForm(collection);
        } else {
            form = new CollectionForm();
        }

        return form;
    }

    /*
     * (non-Javadoc)
     * @see org.springframework.web.servlet.mvc.SimpleFormController#referenceData(javax.servlet.http.HttpServletRequest, java.lang.Object, org.springframework.validation.Errors)
     */
    @SuppressWarnings("rawtypes")
    @Override
    protected Map referenceData(HttpServletRequest request, Object command,
            Errors errors) throws Exception {

        Map<String,Object> model = new HashMap<String,Object>();

        String collectionId = request.getParameter("collectionId");
        if ( StringUtils.isBlank(collectionId) ) {
            model.put("isAdding", true);
        } else {
            model.put("isAdding", false);
        }

        /* make sharing options available to the page
		List<String> sharingOptions = new ArrayList<String>();
		sharingOptions.add(MediaCollection.SHARING_ADMIN);
		sharingOptions.add(MediaCollection.SHARING_PRIVATE);
		sharingOptions.add(MediaCollection.SHARING_PUBLIC);
		sharingOptions.add(MediaCollection.SHARING_SHARED);
		model.put("sharingOptions", sharingOptions); */

        return model;
    }

    /*
     * (non-Javadoc)
     * @see org.springframework.web.servlet.mvc.CancellableFormController#onCancel(javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse, java.lang.Object)
     */
    @Override
    protected ModelAndView onCancel(HttpServletRequest request,
            HttpServletResponse response, Object command) throws Exception {

        CollectionForm form = (CollectionForm) command;

        /*
         *  If this would have been a new collection, send the user to the main
         *  collection listing page.  Otherwise, send the user back to the view page
         *  for the currently-in-edit collection. 
         */

        if (StringUtils.isBlank(form.getId())) {
            request.getRequestDispatcher("listCollections.htm").forward(request, response);
        } else {
            request.getRequestDispatcher("viewCollection.htm?collectionId=".concat(form.getId())).forward(request, response);
        }

        return null;
    }


    private MediaService mediaService;
    public void setMediaService(MediaService service) {
        this.mediaService = service;
    }

    private ExternalLogic external;
    public void setExternal(ExternalLogic external) {
        this.external = external;
    }

}

kaltura/src/main/java/org/sakaiproject/kaltura/tool/EditCollectionMediaController.java
/**
 * Copyright 2010 Unicon (R) Licensed under the
 * Educational Community License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 *
 * http://www.osedu.org/licenses/ECL-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS"
 * BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package org.sakaiproject.kaltura.tool;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;
import org.sakaiproject.kaltura.logic.ExternalLogic;
import org.sakaiproject.kaltura.logic.MediaService;
import org.sakaiproject.kaltura.model.MediaCollection;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.AbstractController;

/**
 * EditCollectionMediaController might in the future handle editing media
 * in an existing Kaltura collection.  Right now, adding and removing media
 * items is handled by two other controllers in this package, and this 
 * controller's submit method should not be called.
 * 
 * @author Aaron Zeckoski, azeckoski@unicon.net
 * @author Jen Bourey, jbourey@unicon.net
 * @version $Revision: 118630 $
 */
public class EditCollectionMediaController extends AbstractController {

    /*
     * (non-Javadoc)
     * @see org.springframework.web.servlet.mvc.AbstractController#handleRequestInternal(javax.servlet.http.HttpServletRequest, javax.servlet.http.HttpServletResponse)
     */
    @Override
    protected ModelAndView handleRequestInternal(HttpServletRequest request,
            HttpServletResponse response) throws Exception {
        Map<String,Object> model = new HashMap<String,Object>();

        /*
         * Retrieve the specified collection from the Kaltura service
         * Fully populate all contained media items and add the collection to the model.
         */

        String collectionId = request.getParameter("collectionId");
        MediaCollection collection = mediaService.getCollection(collectionId, 0, 0); // collection only
        // ensure this page cannot be loaded if the user does not have permission
        if (! collection.isControl() && ! collection.isAddItems()) {
            throw new SecurityException("User ("+external.getCurrentUserId()+") does not have permission to add items to this collection ("+collection+")");
        }
        //mediaService.populateItems(collection.getItems());

        // get the permissions
        String locationId = external.getCurrentLocationId();
        String userId = external.getCurrentUserId();

        model.put("collection", collection);
        // permissions
        model.put("showMyMediaTab", mediaService.isKalturaMyMediaVisible(userId, locationId));
        model.put("isSiteLibraryVisible", mediaService.isSiteLibraryVisible(userId, locationId));
        model.put("canAdministrateKalturaPermissions", external.canAdministrateKalturaPermissions());
        model.put("isKalturaAdmin", mediaService.isKalturaAdmin(userId, locationId));
        model.put("isKalturaManager", mediaService.isKalturaManager(userId, locationId));
        model.put("isKalturaWrite", mediaService.isKalturaWrite(userId, locationId));
        model.put("isKalturaRead", mediaService.isKalturaRead(userId, locationId));
        // get data needed for rendering
        model.put("toolId", external.getCurrentToolId());
        model.put("siteId", StringUtils.substringAfterLast(locationId, "/site/"));
        model.put("currentUserDisplay", external.getCurrentUserDisplayName());

        return new ModelAndView("editCollectionMedia", model);
    }

    private MediaService mediaService;
    public void setMediaService(MediaService service) {
        this.mediaService = service;
    }

    private ExternalLogic external;
    public void setExternal(ExternalLogic external) {
        this.external = external;
    }

}

kaltura/src/main/java/org/sakaiproject/kaltura/tool/UploadMediaController.java
/**
 * Copyright 2010 Unicon (R) Licensed under the
 * Educational Community License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 *
 * http://www.osedu.org/licenses/ECL-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS"
 * BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package org.sakaiproject.kaltura.tool;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang.StringUtils;
import org.sakaiproject.kaltura.logic.KalturaAPIService;
import org.sakaiproject.kaltura.logic.KalturaAPIService.Widget;
import org.sakaiproject.kaltura.logic.MediaService;
import org.sakaiproject.kaltura.logic.ExternalLogic;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.AbstractController;

/**
 * 
 * @author Aaron Zeckoski, azeckoski@unicon.net
 * @version $Revision: 123654 $
 */
public class UploadMediaController extends AbstractController {

    @Override
    protected ModelAndView handleRequestInternal(HttpServletRequest request, HttpServletResponse response) throws Exception {
        Map<String,Object> model = new HashMap<String,Object>();
        String userId = external.getCurrentUserId();
        model.put("currentUserId", userId);
        String locationId = external.getCurrentLocationId();
        model.put("currentLocationId", locationId);

        String widgetPlayerUploadSpecialId = "";
        String widgetPlayerUploadSpecialKS = "";
        if (service.isKalturaUploadSpecial(userId, locationId)) {
            widgetPlayerUploadSpecialId = kalturaAPIService.getKalturaWidgetId(Widget.UPLOADER_SPECIAL);
            widgetPlayerUploadSpecialKS = kalturaAPIService.getKalturaClient(KalturaAPIService.KS_PERM_LIST).getSessionId();
        }
        model.put("uploadSpecialId", widgetPlayerUploadSpecialId);
        model.put("uploadSpecialKS", widgetPlayerUploadSpecialKS);
        model.put("toolId", external.getCurrentToolId());
        model.put("isSiteLibraryVisible", service.isSiteLibraryVisible(userId, locationId));

        String collectionId = request.getParameter("collectionId");
        if (!StringUtils.substringAfterLast(locationId, "/site/").equals(collectionId)) {
            model.put("collectionId", collectionId);
        }

        return new ModelAndView("uploadMedia", model);
    }

    private ExternalLogic external;
    public void setExternal(ExternalLogic external) {
        this.external = external;
    }

    private KalturaAPIService kalturaAPIService;
    public void setKalturaAPIService(KalturaAPIService kalturaAPIService) {
        this.kalturaAPIService = kalturaAPIService;
    }

    private MediaService service;
    public void setService(MediaService service) {
        this.service = service;
    }

}

kaltura/src/main/webapp/WEB-INF/jsp/editCollectionDetails.jsp
<%--

    Copyright 2010 Unicon (R) Licensed under the
    Educational Community License, Version 2.0 (the "License"); you may
    not use this file except in compliance with the License. You may
    obtain a copy of the License at

    http://www.osedu.org/licenses/ECL-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an "AS IS"
    BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
    or implied. See the License for the specific language governing
    permissions and limitations under the License.

--%>
<jsp:directive.include file="/WEB-INF/jsp/includes.jsp" />
<jsp:directive.include file="/WEB-INF/jsp/header.jsp" />

<!-- Portlet -->
<div class="portlet kaltura-gallery view-edit" role="section">
  <!-- Portlet Views -->
  <div class="portlet-views">
    <ul role="tablist" class="fl-tabs fl-tabs-left ui-helper-clearfix view-tabs">
      <c:if test="${isSiteLibraryVisible }">
        <li tabindex="-1" role="tab">
          <a role="link" key="library" href="viewCollection.htm" title="<spring:message code='app.tooltip.view.site.library'/>">
            <span><spring:message code="app.site.library" /></span>
          </a>
        </li>
      </c:if>
      <li class="fl-activeTab" tabindex="0" role="tab">
        <a role="link" key="collections" href="listCollections.htm" title="<spring:message code='app.tooltip.view.media.collection'/>">
          <span><spring:message code="app.collections" /></span>
        </a>
      </li>
    </ul>
    <div class="fl-tab-content tab-content" role="tabpanel">

      <!-- Portlet Toolbar -->
      <div class="toolbar" role="toolbar"></div>

      <!-- Portlet Body -->
      <div class="content portlet-content" role="main">
        <!-- Portlet Title -->
        <div class="titlebar portlet-titlebar" role="sectionhead">
          <!--<div class="breadcrumb">
                <span class="breadcrumb-1"><a href="listCollections.htm">Collections</a></span>
                <span class="separator"> &gt; </span><span class="breadcrumb-2">
                    <a href="viewCollection.htm?collectionId=${collectionForm.id}">${collectionForm.title}</a>
                </span>
            </div>-->
          <h2 class="title" role="heading">
            <c:choose>
              <c:when test="${ isAdding }">
                <spring:message code="app.toolbar.add.collection" />
              </c:when>
              <c:otherwise>
                <spring:message code="app.edit.collection" />
              </c:otherwise>
            </c:choose>
          </h2>
        </div>

        <kaltura:messages />
        <div class="portlet-form">
          <form:form action="editCollectionDetails.htm" method="post" cssClass="button_form" commandName="collectionForm">
            <form:hidden path="id" />
            <table>
              <tr>
                <td class="label required">
                  <form:label path="title">
                    <spring:message code="editCollectionDetails.name" />:</form:label>
                </td>
                <td>
                  <form:input path="title" cssClass="collection_title inputtext" maxlength="200" size="80" />
                  <span class="collection_title_missing error hide"><spring:message code="editCollectionDetails.title.warning" /></span>
                </td>
              </tr>
              <tr>
                <td class="label">
                  <form:label path="title">
                    <spring:message code="editCollectionDetails.description" />:</form:label>
                </td>
                <td>
                  <form:textarea path="description" cssClass="inputtext" cols="80" rows="3" />
                </td>
              </tr>
              <tr>
                <td class="label required">
                  <form:label path="sharing">
                    <spring:message code="editCollectionDetails.management" />:</form:label>
                </td>
                <td>
                  <%-- NOTE: the option keys must match the MediaCollection.SHARING_* constants --%>
                  <form:select path="sharing">
                    <form:option value="admin">
                      <spring:message code="editCollectionDetails.options.instructor" />
                    </form:option>
                    <form:option value="public">
                      <spring:message code="editCollectionDetails.options.community" />
                    </form:option>
                    <form:option value="shared">
                      <spring:message code="editCollectionDetails.options.personal" />
                    </form:option>
                    <form:option value="private">
                      <spring:message code="editCollectionDetails.options.owner" />
                    </form:option>
                  </form:select>
                </td>
              </tr>
              <tr>
                <td class="label">&nbsp;</td>
                <td>
                  <div class="help-legend">
                    <h3>
                      <spring:message code="editCollectionDetails.legend.description" />
                    </h3>
                    <ul>
                      <li>
                        <strong><spring:message code="editCollectionDetails.options.instructor" /></strong>:
                        <spring:message code="editCollectionDetails.legend.instructor.description" />
                      </li>
                      <li>
                        <strong><spring:message code="editCollectionDetails.options.community" /></strong>:
                        <spring:message code="editCollectionDetails.legend.community.description" />
                      </li>
                      <li>
                        <strong><spring:message code="editCollectionDetails.options.personal" /></strong>:
                        <spring:message code="editCollectionDetails.legend.personal.description" />
                      </li>
                      <li>
                        <strong><spring:message code="editCollectionDetails.options.owner" /></strong>:
                        <spring:message code="editCollectionDetails.legend.owner.description" />
                      </li>
                    </ul>
                  </div>
                </td>
              </tr>
            </table>
            <div id="submit_buttons" class="buttons">
              <input id="submit_save" class="button primary save" type="submit" value="save" />
              <input id="submit_cancel" class="button cancel" type="submit" name="_cancel" value="cancel" />
            </div>
            <div id="submit_spinner" style="display:none;text-align: center;">
              <strong><spring:message code="editCollectionDetails.submit.processing" /></strong>
              <br/>
              <img alt="spinner" src="images/ajax-loader.gif">
            </div>
          </form:form>
        </div>
      </div>
      <!-- end: .portlet-content -->
    </div>
    <!-- end: .portlet -->
  </div>
</div>

<script type="text/javascript">
$(document).ready(function() {

    $("form.button_form input:submit").bind("click keypress", function() {
      // store the id of the submit-input on it's enclosing form
        var $form = $(this).parents('form:first');
        $form.data("callerID", this.id);
    });

    // validate the form
    $("form.button_form").submit(function() {
        var $form = $(this);
        // only validate if the submit was used (and not cancel)
        var validate = false;
        if ($form.data("callerID") == "submit_save") {
            validate = true;
        }
        var $ctitle = $form.find(".collection_title");
        var $ctitlemsg = $form.find(".collection_title_missing");
        if (validate && $ctitle.val().length <= 0) {
            $ctitle.addClass("error");
            $ctitlemsg.removeClass("hide");
            return false;
        } else {
            $ctitle.removeClass("error");
            $ctitlemsg.addClass("hide");
            $("#submit_spinner").show(); // turn on the processing spinner
            $("#submit_buttons").hide(); // hide the submit to reduce confusion
            return true;
        }
    });

});
</script>

<jsp:directive.include file="/WEB-INF/jsp/footer.jsp" />

kaltura/src/main/webapp/WEB-INF/jsp/kalclip.jsp
<%--

    Copyright 2010 Unicon (R) Licensed under the
    Educational Community License, Version 2.0 (the "License"); you may
    not use this file except in compliance with the License. You may
    obtain a copy of the License at

    http://www.osedu.org/licenses/ECL-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an "AS IS"
    BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
    or implied. See the License for the specific language governing
    permissions and limitations under the License.

--%>
<jsp:directive.include file="/WEB-INF/jsp/includes.jsp" />
<jsp:directive.include file="/WEB-INF/jsp/header.jsp" />
<script src="<c:url value="/javascript/jquery/jquery.time.stepper.js"/>" type="text/javascript"></script>
<script src="<c:url value="/javascript/kalclip.js"/>" type="text/javascript"></script>
<% /* vars: config, entry, clipperUrl, clipperFlashvars
form_title, save_message, trim_note, json_entry
config: show_embed, overwrite_entry, host, partner_id, kdp_uiconf_id, clipper_uiconf_id, redirect_save, redirect_url
*/ %>
<div>
  <c:choose>
    <c:when test="${fromSiteLibrary}">
      <a id="returnLink" href="viewCollection.htm">
        <spring:message code="uploadMedia.back.site.library" />
      </a>
      &nbsp;
    </c:when>
    <c:otherwise>
      <a id="returnLink" href="viewCollection.htm?collectionId=${collectionId}">
        <spring:message code="uploadMedia.back.collection" />
      </a>
    </c:otherwise>
  </c:choose>
</div>
  <div id="wrapper">
      <object id="kdp3" name="kdp3" type="application/x-shockwave-flash" wmode="window" allowFullScreen="true" allowNetworking="all"  
              allowScriptAccess="always" bgcolor="#000000" height="280" width="500" resource="${ kdpUrl }" data="${ kdpUrl }">
        <param name="allowFullScreen" value="true" />
        <param name="allowNetworking" value="all" />
        <param name="allowScriptAccess" value="always" />
        <param name="wmode" value="window" />
        <param name="bgcolor" value="#000000" />
        <param name="flashVars" value="&steamerType=rtmp&entryId=${ item.kalturaId }" />
        <param name="movie" value="${ kdpUrl }" />
      </object>
      <div id="form" class="form clearfix">
          <div id="newclip">
            <div class="disable"></div>
            <img id="loader" src="images/kalclip/loader.gif" alt="<spring:message code="app.saving" />" />
            <a href="#">${ form_title }</a>
          </div>
          <div id="embed" class="form clearfix">
              <p>${ save_message }</p>
              <br />
              <c:if test="${ config['show_embed'] }">
              <div class="item clearfix">
                  <label><spring:message code="kalclip.embed" /></label>
                  <input id="embedcode" class="text-field" type="text" value="" />
              </div>
              <br />
              </c:if>
          </div>
          <div id="fields">
              ${ trim_note }
              <div class="disable"></div>
              <div class="item clearfix">
                  <label><spring:message code="kalclip.starttime" /></label>
                  <input id="startTime" value="" />
              </div>
              <div class="item clearfix">
                  <label><spring:message code="kalclip.endtime" /></label>
                  <input id="endTime" value="" />
              </div>
              <div class="item clearfix">
                  <label><spring:message code="kalclip.title" /></label>
                  <input id="entry_title" class="text-field" type="text" value="${ item.name } by ${ username }" /><br /><br />
              </div>
              <div class="item clearfix">
                  <label><spring:message code="kalclip.description" /></label>
                  <textarea id="entry_desc">${ item.desc }</textarea><br /><br />
              </div>
          </div>
      </div>
  
      <object id="clipper" name="clipper" type="application/x-shockwave-flash" wmode="window" allowNetworking="all" allowScriptAccess="always" data="${ clipperUrl }">
        <param name="allowNetworking" value="all" />
        <param name="allowScriptAccess" value="always" />
        <param name="wmode" value="window" />
        <param name="bgcolor" value="#f8f8f8" />
        <param name="flashVars" value="${ clipperFlashvars }" />
        <param name="movie" value="${ clipperUrl }" />
      </object>
  
      <div id="actions" class="clearfix">
          <div class="disable"></div>
          <div class="left clearfix">
              <a href="#" id="setStartTime"><spring:message code="kalclip.setin" /></a>
              <a href="#" id="setEndTime"><spring:message code="kalclip.setout" /></a>
          </div>
          <div class="right clearfix">
              <a href="#" id="preview"><spring:message code="kalclip.preview" /></a>
              <span class="seperator"> | </span>
              <a href="#" id="delete"><spring:message code="kalclip.remove" /></a>
          </div>
      </div>
      <c:if test="${ isKalturaWrite }">
          <div id="options" class="clearfix">
              <div>
                  <input id="addToSiteLibrary" type="checkbox"><spring:message code="kalclip.add.to.site.library" />
              </div>
          </div>
      </c:if>
      <div id="buttons">
          <c:if test="${ showReplaceButton }">
              <span id="replace">
                  <span class="disable"></span>
                  <a id="replace_a" href="#" title="<spring:message code='kalclip.tooltip.replace.clip'/>"><spring:message code="kalclip.replace" /></a>
              </span>      
          </c:if>
          <span id="save">
              <span class="disable"></span>
              <a id="save_a" href="#" title="<spring:message code='kalclip.tooltip.save.clip'/>"><spring:message code="kalclip.save" /></a>
          </span>
      </div>
  </div>
  <input type="hidden" id="locationId" value="${ locationId }" />
  <input type="hidden" id="collectionId" value="${ collectionId }" />
  <input type="hidden" id="position" value="${ position }" />
  <script>
  clipApp.init( {
          "config": "${param.config}",
          "host": "${ config['host'] }",
          "partner_id": "${ config['partner_id'] }",
          "entry": ${ json_entry },
          "ks": "${ks}",
          "kdp_uiconf_id": ${ config['kdp_uiconf_id'] },
          "kclip_uiconf_id": ${ config['clipper_uiconf_id'] },
          "redirect_save": ${ config['redirect_save'] ? "true" : "false" },
          "redirect_url": "${ config['redirect_url'] }",
          "overwrite_entry": ${ config['overwrite_entry'] ? "true" : "false" }
  });
  </script>